### ISSUE TITLE
Do not show progress bar when clicking on link to current route

### ISSUE THREAD

**Issue by bombillazo** [beeinger/next-progress#10]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `next-progress@2.2.0` for the project I'm working on.

If we click on a link pointing to the current route, the NProgress bar will show up. This change is so that we do not show the bar if we click, and it points to the current route.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/next-progress/dist/index.js b/node_modules/next-progress/dist/index.js
index 84150e5..707f645 100644
--- a/node_modules/next-progress/dist/index.js
+++ b/node_modules/next-progress/dist/index.js
@@ -26,7 +26,8 @@ var NextProgress = React__default["default"].memo(function (_a) {
     React.useEffect(function () {
         options && NProgress__default["default"].configure(options);
         var timeout;
-        var start = function () {
+        var start = function (e) {
+            if(e === Router.route) return null;
             return (timeout = setTimeout(function () { return NProgress__default["default"].start(); }, delay));
         }, done = function () {
             clearTimeout(timeout);
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by beeinger** [comment]
Good one, will add it

**Comment by beeinger** [comment]
Available in the [latest release](https://github.com/beeinger/next-progress/releases/tag/v2.3.0)
