### ISSUE TITLE
The component sc-global-dAvrxo has been created dynamically?

### ISSUE THREAD

**Issue by siamahnaf** [beeinger/next-progress#4]
Hello, I am using `next-progress` in my project. But I am getting one warning like this-

```
The component sc-global-dAvrxo has been created dynamically.
You may see this warning because you've called styled inside another component.
To resolve this only create new StyledComponents outside of any render method and function component.
```

Actually What is the problem. Here I am using styled component with material-ui(mui)

```
<CacheProvider value={emotionCache}>
      <Head>
        <meta name="viewport" content="initial-scale=1, width=device-width" />
      </Head>
      <ThemeProvider theme={theme}>
        <CssBaseline />
        <NextProgress
          delay={400}
          options={{ showSpinner: false }}
          height="1.5px"
          color="#0EA102"
        />
        <Component {...pageProps} />
      </ThemeProvider>
 </CacheProvider>
```

Here I am calling `next progress` by this away. Can you help me with removing this warning?

**Comment by bitfella** [comment]
Same here. Using `next 12.0.7`, `styled-components 5.3.3` and `next-progress 1.0.8`.

I see this happens because in line 34 of `index.tsx` styles are defined inside the component itself.
They should be defined outside, instead; passing `color`, `customGlobalCss` and `height` props to them.

Are pull requests welcome on this repo? Thanks @beeinger

**Comment by beeinger** [comment]
Yeah sure! Sorry for late response

**Comment by siamahnaf** [comment]
But solutions?

**Comment by bitfella** [comment]
@siamahnaf198 no solutions out of the box, the module should be fixed as stated above. Gonna see if I got time in the next days to take care of that and make a proper pull request to the repo owner. In the meanwhile, have a great weekend 🍻

**Comment by beeinger** [comment]
I have just rewritten the package to eliminate styled-components which were unnecessary in this case, everything works the same apart from the customGlobalCss parameter. No more warnings and it's way faster, cleaner and flexible.
