### ISSUE TITLE
Ship with minified CSS inside the <style> tag

### ISSUE THREAD

**Issue by klogins** [beeinger/next-progress#5]
I have noticed the CSS for `next-progress` adds `<style>` with unminified styles. It could be great to have it minified with removed comments. Some small amount of bytes could be saved :) 

![image](https://user-images.githubusercontent.com/52526114/179604011-a422df47-6d22-46e2-accd-d38ecee18559.png)

**Comment by beeinger** [comment]
Cool, will do that.

**Comment by beeinger** [comment]
Available in the [latest release](https://github.com/beeinger/next-progress/releases/tag/v2.3.0)
